/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Song } from './song';


export interface ChartResponse { 
    top1?: Array<number>;
    top2?: Array<number>;
    top3?: Array<number>;
    songs?: Array<Song>;
}

