/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SafeUrl } from '@angular/platform-browser';
import { Composer } from './composer';
import { Singer } from './singer';
import { SubCategory } from './subCategory';
import { Trending } from './trending';


export interface Song { 
    id?: number;
    songName?: string;
    duration?: number;
    image?: Array<string>;
    imageName?: string;
    views?: number;
    imgUrl: SafeUrl;
    trending?: Set<Trending>;
    singer?: Singer;
    composer?: Composer;
    subCategory?: SubCategory;
}

