/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Song } from './song';


export interface UserDTO { 
    userName?: string;
    password?: string;
    gender?: UserDTO.GenderEnum;
    birthOfDate?: string;
    firstName?: string;
    lastName?: string;
    mobile?: string;
    email?: string;
    favoriteSongs?: Set<Song>;
    roles?: Set<string>;
}
export namespace UserDTO {
    export type GenderEnum = 'MALE' | 'FEMALE' | 'OTHER';
    export const GenderEnum = {
        Male: 'MALE' as GenderEnum,
        Female: 'FEMALE' as GenderEnum,
        Other: 'OTHER' as GenderEnum
    };
}


